/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './user-details';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '../../providers/github-users';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/badge/badge.ngfactory';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from 'ionic-angular/components/app/app';
import * as import26 from 'ionic-angular/components/toolbar/toolbar';
import * as import27 from 'ionic-angular/util/keyboard';
import * as import28 from '@angular/core/src/zone/ng_zone';
import * as import29 from 'ionic-angular/components/tabs/tabs';
import * as import30 from 'ionic-angular/gestures/gesture-controller';
import * as import31 from 'ionic-angular/util/form';
import * as import32 from 'ionic-angular/components/item/item-reorder';
import * as import33 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import34 from 'ionic-angular/components/navbar/navbar';
import * as import35 from 'ionic-angular/components/label/label';
import * as import36 from 'ionic-angular/components/badge/badge';
import * as import37 from 'ionic-angular/components/item/item';
import * as import38 from 'ionic-angular/components/list/list';
import * as import39 from 'ionic-angular/components/content/content';
export class Wrapper_UserDetailsPage {
  context:import0.UserDetailsPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.UserDetailsPage(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_UserDetailsPage_Host:import2.RenderComponentType = (null as any);
class _View_UserDetailsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _UserDetailsPage_0_4:Wrapper_UserDetailsPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserDetailsPage_Host0,renderType_UserDetailsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-user-details',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserDetailsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserDetailsPage_0_4 = new Wrapper_UserDetailsPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.GithubUsers));
    this._appEl_0.initComponent(this._UserDetailsPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._UserDetailsPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.UserDetailsPage) && (0 === requestNodeIndex))) { return this._UserDetailsPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._UserDetailsPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserDetailsPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_UserDetailsPage_Host === (null as any))) { (renderType_UserDetailsPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_UserDetailsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserDetailsPageNgFactory:import12.ComponentFactory<import0.UserDetailsPage> = new import12.ComponentFactory<import0.UserDetailsPage>('page-user-details',viewFactory_UserDetailsPage_Host0,import0.UserDetailsPage);
const styles_UserDetailsPage:any[] = ([] as any[]);
var renderType_UserDetailsPage:import2.RenderComponentType = (null as any);
class _View_UserDetailsPage0 extends import1.AppView<import0.UserDetailsPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import13.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import14.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import15.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import16.Wrapper_Content;
  _text_11:any;
  _el_12:any;
  _List_12_3:import17.Wrapper_List;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Item_14_4:import18.Wrapper_Item;
  _ItemContent_14_5:import18.Wrapper_ItemContent;
  _query_Label_14_0:import19.QueryList<any>;
  _query_Button_14_1:import19.QueryList<any>;
  _query_Icon_14_2:import19.QueryList<any>;
  _text_15:any;
  _el_16:any;
  _Label_16_3:import20.Wrapper_Label;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _Badge_19_3:import21.Wrapper_Badge;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Item_23_4:import18.Wrapper_Item;
  _ItemContent_23_5:import18.Wrapper_ItemContent;
  _query_Label_23_0:import19.QueryList<any>;
  _query_Button_23_1:import19.QueryList<any>;
  _query_Icon_23_2:import19.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Label_25_3:import20.Wrapper_Label;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _Badge_28_3:import21.Wrapper_Badge;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import3.AppElement;
  _Item_32_4:import18.Wrapper_Item;
  _ItemContent_32_5:import18.Wrapper_ItemContent;
  _query_Label_32_0:import19.QueryList<any>;
  _query_Button_32_1:import19.QueryList<any>;
  _query_Icon_32_2:import19.QueryList<any>;
  _text_33:any;
  _el_34:any;
  _Label_34_3:import20.Wrapper_Label;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _Badge_37_3:import21.Wrapper_Badge;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import3.AppElement;
  _Item_41_4:import18.Wrapper_Item;
  _ItemContent_41_5:import18.Wrapper_ItemContent;
  _query_Label_41_0:import19.QueryList<any>;
  _query_Button_41_1:import19.QueryList<any>;
  _query_Icon_41_2:import19.QueryList<any>;
  _text_42:any;
  _el_43:any;
  _Label_43_3:import20.Wrapper_Label;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _Badge_46_3:import21.Wrapper_Badge;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserDetailsPage0,renderType_UserDetailsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import13.Wrapper_Header(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import24.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import25.App),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import15.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import15.Wrapper_ToolbarTitle(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import26.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import16.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import16.Wrapper_Content(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import25.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import29.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_12_3 = new import17.Wrapper_List(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import30.GestureController));
    this._text_13 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','item item-block');
    this._appEl_14 = new import3.AppElement(14,12,this,this._el_14);
    var compView_14:any = import18.viewFactory_Item0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Item_14_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_14_5 = new import18.Wrapper_ItemContent();
    this._query_Label_14_0 = new import19.QueryList<any>();
    this._query_Button_14_1 = new import19.QueryList<any>();
    this._query_Icon_14_2 = new import19.QueryList<any>();
    this._appEl_14.initComponent(this._Item_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_16_3 = new import20.Wrapper_Label(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_16),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Followers',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-badge',(null as any));
    this.renderer.setElementAttribute(this._el_19,'item-right','');
    this._Badge_19_3 = new import21.Wrapper_Badge(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_14_0.reset([this._Label_16_3.context]);
    this._Item_14_4.context.contentLabel = this._query_Label_14_0.first;
    compView_14.create(this._Item_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_16]),
      ([] as any[]).concat([
        this._text_15,
        this._text_18,
        this._text_21
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_19])
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_12,'\n     ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this._appEl_23 = new import3.AppElement(23,12,this,this._el_23);
    var compView_23:any = import18.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_23_5 = new import18.Wrapper_ItemContent();
    this._query_Label_23_0 = new import19.QueryList<any>();
    this._query_Button_23_1 = new import19.QueryList<any>();
    this._query_Icon_23_2 = new import19.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_25_3 = new import20.Wrapper_Label(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_25),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Following',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-badge',(null as any));
    this.renderer.setElementAttribute(this._el_28,'item-right','');
    this._Badge_28_3 = new import21.Wrapper_Badge(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_23_0.reset([this._Label_25_3.context]);
    this._Item_23_4.context.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_25]),
      ([] as any[]).concat([
        this._text_24,
        this._text_27,
        this._text_30
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_28])
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(this._el_12,'\n     ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','item item-block');
    this._appEl_32 = new import3.AppElement(32,12,this,this._el_32);
    var compView_32:any = import18.viewFactory_Item0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Item_32_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_32),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_32_5 = new import18.Wrapper_ItemContent();
    this._query_Label_32_0 = new import19.QueryList<any>();
    this._query_Button_32_1 = new import19.QueryList<any>();
    this._query_Icon_32_2 = new import19.QueryList<any>();
    this._appEl_32.initComponent(this._Item_32_4.context,([] as any[]),compView_32);
    this._text_33 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_34_3 = new import20.Wrapper_Label(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_34),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'Repos',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-badge',(null as any));
    this.renderer.setElementAttribute(this._el_37,'item-right','');
    this._Badge_37_3 = new import21.Wrapper_Badge(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_37),this.renderer);
    this._text_38 = this.renderer.createText(this._el_37,'',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_32_0.reset([this._Label_34_3.context]);
    this._Item_32_4.context.contentLabel = this._query_Label_32_0.first;
    compView_32.create(this._Item_32_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_34]),
      ([] as any[]).concat([
        this._text_33,
        this._text_36,
        this._text_39
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_37])
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(this._el_12,'\n     ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','item item-block');
    this._appEl_41 = new import3.AppElement(41,12,this,this._el_41);
    var compView_41:any = import18.viewFactory_Item0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Item_41_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_41),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_41_5 = new import18.Wrapper_ItemContent();
    this._query_Label_41_0 = new import19.QueryList<any>();
    this._query_Button_41_1 = new import19.QueryList<any>();
    this._query_Icon_41_2 = new import19.QueryList<any>();
    this._appEl_41.initComponent(this._Item_41_4.context,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_43_3 = new import20.Wrapper_Label(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_43),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Gists',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_46 = this.renderer.createElement((null as any),'ion-badge',(null as any));
    this.renderer.setElementAttribute(this._el_46,'item-right','');
    this._Badge_46_3 = new import21.Wrapper_Badge(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_46),this.renderer);
    this._text_47 = this.renderer.createText(this._el_46,'',(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_41_0.reset([this._Label_43_3.context]);
    this._Item_41_4.context.contentLabel = this._query_Label_41_0.first;
    compView_41.create(this._Item_41_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_43]),
      ([] as any[]).concat([
        this._text_42,
        this._text_45,
        this._text_48
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_46])
    ]
    ,(null as any));
    this._text_49 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._text_50 = this.renderer.createText((null as any),'    \n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_50
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import34.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import26.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import35.Label) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Label_16_3.context; }
    if (((token === import36.Badge) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Badge_19_3.context; }
    if (((token === import37.Item) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_14_4.context; }
    if (((token === import37.ItemContent) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_14_5.context; }
    if (((token === import35.Label) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Label_25_3.context; }
    if (((token === import36.Badge) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Badge_28_3.context; }
    if (((token === import37.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Item_23_4.context; }
    if (((token === import37.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._ItemContent_23_5.context; }
    if (((token === import35.Label) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Label_34_3.context; }
    if (((token === import36.Badge) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Badge_37_3.context; }
    if (((token === import37.Item) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Item_32_4.context; }
    if (((token === import37.ItemContent) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ItemContent_32_5.context; }
    if (((token === import35.Label) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Label_43_3.context; }
    if (((token === import36.Badge) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Badge_46_3.context; }
    if (((token === import37.Item) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Item_41_4.context; }
    if (((token === import37.ItemContent) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._ItemContent_41_5.context; }
    if (((token === import38.List) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._List_12_3.context; }
    if (((token === import39.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this._List_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    if (this._Item_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._ItemContent_14_5.detectChangesInternal(this,this._el_14,throwOnChange);
    this._Label_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    this._Badge_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    if (this._Item_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._ItemContent_23_5.detectChangesInternal(this,this._el_23,throwOnChange);
    this._Label_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    this._Badge_28_3.detectChangesInternal(this,this._el_28,throwOnChange);
    if (this._Item_32_4.detectChangesInternal(this,this._el_32,throwOnChange)) { this._appEl_32.componentView.markAsCheckOnce(); }
    this._ItemContent_32_5.detectChangesInternal(this,this._el_32,throwOnChange);
    this._Label_34_3.detectChangesInternal(this,this._el_34,throwOnChange);
    this._Badge_37_3.detectChangesInternal(this,this._el_37,throwOnChange);
    if (this._Item_41_4.detectChangesInternal(this,this._el_41,throwOnChange)) { this._appEl_41.componentView.markAsCheckOnce(); }
    this._ItemContent_41_5.detectChangesInternal(this,this._el_41,throwOnChange);
    this._Label_43_3.detectChangesInternal(this,this._el_43,throwOnChange);
    this._Badge_46_3.detectChangesInternal(this,this._el_46,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_14_1.dirty) {
        this._query_Button_14_1.reset(([] as any[]));
        this._Item_14_4.context._buttons = this._query_Button_14_1;
        this._query_Button_14_1.notifyOnChanges();
      }
      if (this._query_Icon_14_2.dirty) {
        this._query_Icon_14_2.reset(([] as any[]));
        this._Item_14_4.context._icons = this._query_Icon_14_2;
        this._query_Icon_14_2.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset(([] as any[]));
        this._Item_23_4.context._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset(([] as any[]));
        this._Item_23_4.context._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_Button_32_1.dirty) {
        this._query_Button_32_1.reset(([] as any[]));
        this._Item_32_4.context._buttons = this._query_Button_32_1;
        this._query_Button_32_1.notifyOnChanges();
      }
      if (this._query_Icon_32_2.dirty) {
        this._query_Icon_32_2.reset(([] as any[]));
        this._Item_32_4.context._icons = this._query_Icon_32_2;
        this._query_Icon_32_2.notifyOnChanges();
      }
      if (this._query_Button_41_1.dirty) {
        this._query_Button_41_1.reset(([] as any[]));
        this._Item_41_4.context._buttons = this._query_Button_41_1;
        this._query_Button_41_1.notifyOnChanges();
      }
      if (this._query_Icon_41_2.dirty) {
        this._query_Icon_41_2.reset(([] as any[]));
        this._Item_41_4.context._icons = this._query_Icon_41_2;
        this._query_Icon_41_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_14_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_32_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_41_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.login,'\'s details');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_6,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',((this.context.user == (null as any))? (null as any): this.context.user.followers),'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_20,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',((this.context.user == (null as any))? (null as any): this.context.user.following),'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_29,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',((this.context.user == (null as any))? (null as any): this.context.user.public_repos),'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_38,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'',((this.context.user == (null as any))? (null as any): this.context.user.public_gists),'');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_47,currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_10_4.context.ngOnDestroy();
  }
}
export function viewFactory_UserDetailsPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.UserDetailsPage> {
  if ((renderType_UserDetailsPage === (null as any))) { (renderType_UserDetailsPage = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_UserDetailsPage,{})); }
  return new _View_UserDetailsPage0(viewUtils,parentInjector,declarationEl);
}